# -*- coding: utf-8 -*-
"""BMI_Calc.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RmM5-BPiSAc9_GKxb_87fiQ7Hkv78t3N
"""

#BMI categories
bmi_categories = {
    "Underweight": (None, 18.4),
    "Normal": (18.5, 24.9),
    "Overweight": (25.0, 29.9),
    "Obese": (30.0, None),
}

#user input
weight = float(input("Enter your weight (kg): "))
height = float(input("Enter your height (m): "))

# Calculate BMI
bmi = weight / (height ** 2)

# Find the corresponding BMI category
bmi_category = None
for category, (lower_bound, upper_bound) in bmi_categories.items():
    if (lower_bound is None or bmi >= lower_bound) and (upper_bound is None or bmi < upper_bound):
        bmi_category = category
        break

# Display results
print(f"Your BMI is {bmi:.2f}.")
if bmi_category is not None:
    print(f"BMI category: {bmi_category}")
else:
    print("Error: Could not determine BMI category.")